language: node_js
dist: focal
os:
  - linux
  # - osx
  # - windows
env:
  - LANGUAGE=javascript
  - LANGUAGE=typescript
node_js: # a good example: https://github.com/pillarjs/router/blob/master/.travis.yml
  - "10"
  # - "11"
  - "12"
  - "13"
  - "14"
  - lts/*
  - node
sudo: false
cache:
  directories:
    - node_modules
before_script:
  - sudo apt-get install -y clang-10 clang-format-10
  - clang --version
  - clang-format --version
  - npm run change:language -- $LANGUAGE
scripts:
  - set -e
  - npm i
  - npm run prettier:write
  - npm run lint:write
  - npm run jscpd
  - npm run test
  - npm run test:junit
  - npm run build
# after_script:
  - if [[ $TRAVIS_NODE_VERSION == '12' && $TRAVIS_OS_NAME == 'linux' ]]; then npm run docs;
    if [[ $LANGUAGE == 'typescript' ]]; then sonar-scanner; fi;
    fi
notifications:
  email:
    recipients:
      - dragos.cirjan@gmail.com
    on_success: never
    on_failure: always
addons:
  sonarcloud:
    organization: "templ-project"
    token:
      secure: "hpZuOt/pINKrPzp+rrZELo8WqOFWEV824lOvCxHFiUXIIr9KFGq1MnqBX28/b9BSUcdT2NOMsi/c+MVfrmf0WnxXPXAybAVe+N7L93BMePMqRvqVtxRXuPhgFY3f/voLyCx4dhX9r0k7dE6qnp4zkpuIQr6lDqjsaMrxXE3PiG/E4i6roj2Y/msbZ+aU7ii17u38SGU6amJcHfbaVlQNji6QIizvswyXEEePnpJ4yA0j6Xtpg+rc1PzqzFwCxfmGDEY4xdc/tpepNcAQxDhoXJe99HJO2odPgvXyuow+M5/ZlDeLDTQXrKLXd2K3EZfYuOUTtin/LvCLlVd+e5vlxrgfLB3jxHzpB/zeILPiqKE3FHVYbcJKAuKc/E4lx6PQvLO53w0vjGibsmsnvF5KNXKD1XWRPoVcuEloRr4RZ1AU8JEXu/vswgBzfGmWEWcLq6x2i+mT1JP4TyV3RahV7wclKfmPx6dS48JtRfpxkkfc4EZV3ThzINQPqDSzxD7Y2wVn5LhBCMcwCKMKWGxRRTY0kIh7Pgly4M9cGrBR7xYesJlfKGBnQfEbvv6D8p5O12hizjWybNVc9UvrbWNeVL7TkBSc5g54+BnC3VokwYr6hbQ3YglA+4NsNKyQY3c9fz5+22g4CqKgGK6lvkxP5/MBp0OkFQ+1ZcqTAazvNzo="
